version: '3.8'

services:
  html-to-png:
    build:
      context: .
      dockerfile: ./Dockerfile
   # ports:
   #   - "8080:8080"
    # Uncomment the following line if you want the container to start automatically
    # command: ["./png-linux"]