
server {
    listen 80;
    listen [::]:80;
    #listen 443 ssl;
    #listen [::]:443 ssl;

    #ssl_certificate /etc/nginx/ssl/microservices.dev.studenthub.co.crt;
    #ssl_certificate_key /etc/nginx/ssl/microservices.dev.studenthub.co.key;

    #location /bawes-doc-updater/ {
    #    proxy_pass http://doc-updater.railway.internal:3003/;
    #    proxy_set_header Host $host;
    #    proxy_set_header X-Real-IP $remote_addr;
    #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #    proxy_set_header X-Forwarded-Proto $scheme;
    #}

    location /linear/ {
        proxy_pass http://linear.railway.internal:3002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /yeastar-voicemails/ {
        proxy_pass http://yeastar-voicemails.railway.internal:3001/;  # Example: Forwarding requests to an API running on port proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
 